#
#  ÛÛÛÛÛÛ   ÛÛÛÛÛÛ                     ÛÛÛ                ÛÛÛÛÛÛÛÛÛ                         ÛÛÛÛÛÛ   ÛÛÛÛÛ
# °°ÛÛÛÛÛÛ ÛÛÛÛÛÛ                     °°°                ÛÛÛ°°°°°ÛÛÛ                       ÛÛÛ°°ÛÛÛ °°ÛÛÛ
  # °ÛÛÛ°ÛÛÛÛÛ°ÛÛÛ   ÛÛÛÛÛÛ    ÛÛÛÛÛÛÛ ÛÛÛÛ   ÛÛÛÛÛÛ     ÛÛÛ     °°°  ÛÛÛÛÛÛÛÛ   ÛÛÛÛÛÛ    °ÛÛÛ °°°  ÛÛÛÛÛÛÛ
  # °ÛÛÛ°°ÛÛÛ °ÛÛÛ  °°°°°ÛÛÛ  ÛÛÛ°°ÛÛÛ°°ÛÛÛ  ÛÛÛ°°ÛÛÛ   °ÛÛÛ         °°ÛÛÛ°°ÛÛÛ °°°°°ÛÛÛ  ÛÛÛÛÛÛÛ   °°°ÛÛÛ°
  # °ÛÛÛ °°°  °ÛÛÛ   ÛÛÛÛÛÛÛ °ÛÛÛ °ÛÛÛ °ÛÛÛ °ÛÛÛ °°°    °ÛÛÛ          °ÛÛÛ °°°   ÛÛÛÛÛÛÛ °°°ÛÛÛ°      °ÛÛÛ
  # °ÛÛÛ      °ÛÛÛ  ÛÛÛ°°ÛÛÛ °ÛÛÛ °ÛÛÛ °ÛÛÛ °ÛÛÛ  ÛÛÛ   °°ÛÛÛ     ÛÛÛ °ÛÛÛ      ÛÛÛ°°ÛÛÛ   °ÛÛÛ       °ÛÛÛ ÛÛÛ
  # ÛÛÛÛÛ     ÛÛÛÛÛ°°ÛÛÛÛÛÛÛÛ°°ÛÛÛÛÛÛÛ ÛÛÛÛÛ°°ÛÛÛÛÛÛ     °°ÛÛÛÛÛÛÛÛÛ  ÛÛÛÛÛ    °°ÛÛÛÛÛÛÛÛ  ÛÛÛÛÛ      °°ÛÛÛÛÛ
  #°°°°°     °°°°°  °°°°°°°°  °°°°°ÛÛÛ°°°°°  °°°°°°       °°°°°°°°°  °°°°°      °°°°°°°°  °°°°°        °°°°°
  #                           ÛÛÛ °ÛÛÛ
  #                          °°ÛÛÛÛÛÛ
  #                           °°°°°°
  # A plugin by Perotin
#
# Welcome to a world of Magic! Some informative information will be put below this so please check them out!
# ------------------------------------------------------------------------------------------------------




#
#
#    ÛÛÛÛÛÛÛ               ÛÛÛÛÛ     ÛÛÛ
#  ÛÛÛ°°°°°ÛÛÛ            °°ÛÛÛ     °°°
# ÛÛÛ     °°ÛÛÛ ÛÛÛÛÛÛÛÛ  ÛÛÛÛÛÛÛ   ÛÛÛÛ   ÛÛÛÛÛÛ  ÛÛÛÛÛÛÛÛ    ÛÛÛÛÛ
#°ÛÛÛ      °ÛÛÛ°°ÛÛÛ°°ÛÛÛ°°°ÛÛÛ°   °°ÛÛÛ  ÛÛÛ°°ÛÛÛ°°ÛÛÛ°°ÛÛÛ  ÛÛÛ°°
#°ÛÛÛ      °ÛÛÛ °ÛÛÛ °ÛÛÛ  °ÛÛÛ     °ÛÛÛ °ÛÛÛ °ÛÛÛ °ÛÛÛ °ÛÛÛ °°ÛÛÛÛÛ
#°°ÛÛÛ     ÛÛÛ  °ÛÛÛ °ÛÛÛ  °ÛÛÛ ÛÛÛ °ÛÛÛ °ÛÛÛ °ÛÛÛ °ÛÛÛ °ÛÛÛ  °°°°ÛÛÛ
# °°°ÛÛÛÛÛÛÛ°   °ÛÛÛÛÛÛÛ   °°ÛÛÛÛÛ  ÛÛÛÛÛ°°ÛÛÛÛÛÛ  ÛÛÛÛ ÛÛÛÛÛ ÛÛÛÛÛÛ
#   °°°°°°°     °ÛÛÛ°°°     °°°°°  °°°°°  °°°°°°  °°°° °°°°° °°°°°°
 #              °ÛÛÛ
  #             ÛÛÛÛÛ
   #           °°°°°


# The next section will pertain to giving players their first wands! Hooray!
# But first we must decide on how we ara going to do this.
# Should we randomize their wand and give it to them or not give them a wand at all and let you do it?
# Setting this to true will give new players a random wand with a random length and core
randomize-first-wand: true


